url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Kathrina Arrocha Umpiérrez
email: kathrina96@gmail.com
description: "Estudiante en último curso de ingeniería informática en la universidad de la Laguna."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: https://twitter.com/ArrochaKathrina?lang=es
    - title: facebook
      url: https://www.facebook.com/kathrina.arrochaumpierrez
    - title: github
      url: https://github.com/kathrinaAU
    - title: linkedin
      url: https://www.linkedin.com/in/kathrina-arrocha-umpi%C3%A9rrez-60868a189/
    - title: infojobs
      url: https://www.infojobs.net/candidate/cv/view/index.xhtml?dgv=2374575585142427313

# Postal address (add as many lines as necessary)
address:
  - line: Arrecife, Lanzarote 35500

# Build settings
markdown: kramdown
permalink: pretty